# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: Forest
  theme_night: Dark
  font: native_noto
  font_size: m

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: 'é«˜æ–°æŠ€æœ¯; ç§‘æŠ€æœåŠ¡; æ•°æ™ºå¹³å°; äº’è”ç½‘ç”Ÿæ€; ç”Ÿæ€äº’è”ç½‘'
    org_name: '[ä¾‹] ğŸ’°ğŸ’µğŸ–§æœªæ¥é‡‘èç§‘æŠ€å®éªŒå®¤ Future Fin-Tech Lab [ç ”ç©¶ç»„ã€æ•™ç ”å®¤ã€ç ”ç©¶å®¤ã€å®éªŒå®¤æˆ–ç§‘ç ”ç»„ç»‡]'
    description: 'åˆ›æ–°æœªæ¥é‡‘èç§‘æŠ€çš„æ ‡å‡†åŠè®¾è®¡'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    # Align menu links: left (l), center (c), or right (r)
    align: r
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Â© {year} Oxford Roadmapping æ¾³æªæ£®æ•°æ™ºå¯ä»£å®¢ï¼åŸ¹è®­ {license}ï¼ŒåŸºäºhttps://docs.hugoblox.comä»£ç '
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/oxon8/groupeg/'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
